export enum DietaryRestriction {
    NONE = "NONE",
    CELIAC = "CELIAC",
    DIABETIC = "DIABETIC",
    LACTOSE_INTOLERANT = "LACTOSE_INTOLERANT",
    VEGAN = "VEGAN",
    VEGETARIAN = "VEGETARIAN",
    FENILCETONURIA = "FENILCETONURIA",
    LOW_SODIUM = "LOW_SODIUM",
    LOW_FAT = "LOW_FAT",
    NO_FLOUR = "NO_FLOUR",
    NO_SUGAR = "NO_SUGAR"
}

export enum FoodCategory {
    MEAT = "MEAT",
    FISH = "FISH",
    VEGETABLES = "VEGETABLES",
    FRUITS = "FRUITS",
    DAIRY = "DAIRY",
    GRAINS = "GRAINS",
    LEGUMES = "LEGUMES",
    SWEETS = "SWEETS",
    BAKERY = "BAKERY",
    BEVERAGES = "BEVERAGES",
    SNACKS = "SNACKS",
    CONDIMENTS = "CONDIMENTS",
    FATS = "FATS",
    OTHERS = "OTHERS"
}

export enum FoodUnit {
    KILOGRAM = "KILOGRAM",
    GRAM = "GRAM",
    LITER = "LITER",
    MILLILITER = "MILLILITER",
    CUP = "CUP",
    UNIT = "UNIT",
    TABLESPOON = "TABLESPOON",
    PINCH = "PINCH",
    CLOVE = "CLOVE",
    STRIPS = "STRIPS",
    LEAVES = "LEAVES",
    BRANCHES = "BRANCHES",
    SLICE = "SLICE"
}

// Cocinas del mundo
export enum Cuisine {
    ITALIAN = "ITALIAN",
    MEXICAN = "MEXICAN",
    CHINESE = "CHINESE",
    JAPANESE = "JAPANESE",
    MEDITERRANEAN = "MEDITERRANEAN",
    AMERICAN = "AMERICAN",
    LATIN = "LATIN",
    BAKERY = "BAKERY",
    FASTFOOD = "FASTFOOD",
    VEGGIE = "VEGGIE",
    INDIAN = "INDIAN",
    FRENCH = "FRENCH",
    INTERNATIONAL = "INTERNATIONAL"
}

export enum CulinaryCategory {
    BREAKFAST = "BREAKFAST",
    LUNCH = "LUNCH",
    SIDE = "SIDE",
    DINNER = "DINNER",
    SNACK = "SNACK",
    DESSERT = "DESSERT",
    DRINK = "DRINK"
}

export enum Goal {
    NONE = "NONE",
    GAIN_MUSCLE = "GAIN_MUSCLE",
    LOSE_WEIGHT = "LOSE_WEIGHT",
    MAINTAIN_WEIGHT = "MAINTAIN_WEIGHT",
    REDUCE_FAT = "REDUCE_FAT",
    REDUCE_SUGAR = "REDUCE_SUGAR",
    REDUCE_CARBS = "REDUCE_CARBS"
}

// Características nutricionales
export enum NutritionalProperty {
    HIGH_PROTEIN = "HIGH_PROTEIN",
    LOW_CARB = "LOW_CARB",
    LOW_FAT = "LOW_FAT",
    HIGH_FIBER = "HIGH_FIBER",
    SUGAR_FREE = "SUGAR_FREE",
    GLUTEN_FREE = "GLUTEN_FREE",
    HIGH_SUGAR = "HIGH_SUGAR",
    HIGH_FAT = "HIGH_FAT",
    HIGH_CARBS = "HIGH_CARBS",
    DAIRY_FREE = "DAIRY_FREE",
}

export enum ActivityLevel {
    SEDENTARY = "SEDENTARY",
    LIGHTLY_ACTIVE = "LIGHTLY_ACTIVE",
    MODERATELY_ACTIVE = "MODERATELY_ACTIVE",
    VERY_ACTIVE = "VERY_ACTIVE",
    EXTRA_ACTIVE = "EXTRA_ACTIVE"
}

export enum DietType {
    NINGUNA = "NIGNUNA",
    HIPOCALORICA = "HIPOCALORICA",
    AYUNO_INTERMITENTE = "AYUNO_INTERMITENTE",
    CETOGENICA = "CETOGENICA",
    DETOX = "DETOX",
    BALANCEADA = "BALANCEADA",
    PALEO = "PALEO",
}
